version: '3'

services:
  nginx:
    image: educleite/nginx-video-aula:latest
    ports:
      - "8080:80"
    #volumes:
    #  - ./html:/var/share/nginx/html

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydbteste
    volumes:
      - ./data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=rabbitmqtest
    volumes: 
      - ./data-rabbitmq:/var/lib/rabbitmq
